// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tripservice.proto

package trippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pickup        *Coordinate            `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripRequest) Reset() {
	*x = PreviewTripRequest{}
	mi := &file_tripservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripRequest) ProtoMessage() {}

func (x *PreviewTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripRequest.ProtoReflect.Descriptor instead.
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreviewTripRequest) GetPickup() *Coordinate {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *PreviewTripRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

type PreviewTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	RideFares     []*RideFare            `protobuf:"bytes,3,rep,name=ride_fares,json=rideFares,proto3" json:"ride_fares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripResponse) Reset() {
	*x = PreviewTripResponse{}
	mi := &file_tripservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripResponse) ProtoMessage() {}

func (x *PreviewTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripResponse.ProtoReflect.Descriptor instead.
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PreviewTripResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *PreviewTripResponse) GetRideFares() []*RideFare {
	if x != nil {
		return x.RideFares
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_tripservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{2}
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Geometry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   []*Coordinate          `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Geometry) Reset() {
	*x = Geometry{}
	mi := &file_tripservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Geometry) ProtoMessage() {}

func (x *Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Geometry.ProtoReflect.Descriptor instead.
func (*Geometry) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{3}
}

func (x *Geometry) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geometry      []*Geometry            `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_tripservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetGeometry() []*Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *Route) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Route) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RideFare struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PackageSlug       string                 `protobuf:"bytes,3,opt,name=package_slug,json=packageSlug,proto3" json:"package_slug,omitempty"`
	TotalPriceInCents float64                `protobuf:"fixed64,4,opt,name=total_price_in_cents,json=totalPriceInCents,proto3" json:"total_price_in_cents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RideFare) Reset() {
	*x = RideFare{}
	mi := &file_tripservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideFare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideFare) ProtoMessage() {}

func (x *RideFare) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideFare.ProtoReflect.Descriptor instead.
func (*RideFare) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{5}
}

func (x *RideFare) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RideFare) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RideFare) GetPackageSlug() string {
	if x != nil {
		return x.PackageSlug
	}
	return ""
}

func (x *RideFare) GetTotalPriceInCents() float64 {
	if x != nil {
		return x.TotalPriceInCents
	}
	return 0
}

// Part of the exercise starter code
type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideFareId    string                 `protobuf:"bytes,1,opt,name=ride_fare_id,json=rideFareId,proto3" json:"ride_fare_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_tripservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTripRequest) GetRideFareId() string {
	if x != nil {
		return x.RideFareId
	}
	return ""
}

func (x *CreateTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_tripservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tripservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_tripservice_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

var File_tripservice_proto protoreflect.FileDescriptor

const file_tripservice_proto_rawDesc = "" +
	"\n" +
	"\x11tripservice.proto\x12\x11rideshare.trip.v1\"\xa5\x01\n" +
	"\x12PreviewTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x125\n" +
	"\x06pickup\x18\x02 \x01(\v2\x1d.rideshare.trip.v1.CoordinateR\x06pickup\x12?\n" +
	"\vdestination\x18\x03 \x01(\v2\x1d.rideshare.trip.v1.CoordinateR\vdestination\"\x9a\x01\n" +
	"\x13PreviewTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12.\n" +
	"\x05route\x18\x02 \x01(\v2\x18.rideshare.trip.v1.RouteR\x05route\x12:\n" +
	"\n" +
	"ride_fares\x18\x03 \x03(\v2\x1b.rideshare.trip.v1.RideFareR\trideFares\"F\n" +
	"\n" +
	"Coordinate\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"K\n" +
	"\bGeometry\x12?\n" +
	"\vcoordinates\x18\x01 \x03(\v2\x1d.rideshare.trip.v1.CoordinateR\vcoordinates\"x\n" +
	"\x05Route\x127\n" +
	"\bgeometry\x18\x01 \x03(\v2\x1b.rideshare.trip.v1.GeometryR\bgeometry\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x01R\bduration\"\x87\x01\n" +
	"\bRideFare\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fpackage_slug\x18\x03 \x01(\tR\vpackageSlug\x12/\n" +
	"\x14total_price_in_cents\x18\x04 \x01(\x01R\x11totalPriceInCents\"N\n" +
	"\x11CreateTripRequest\x12 \n" +
	"\fride_fare_id\x18\x01 \x01(\tR\n" +
	"rideFareId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x12CreateTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId2k\n" +
	"\vTripService\x12\\\n" +
	"\vPreviewTrip\x12%.rideshare.trip.v1.PreviewTripRequest\x1a&.rideshare.trip.v1.PreviewTripResponseB<Z:github.com/iamonah/rideshare/shared/proto/pb/trippb;trippbb\x06proto3"

var (
	file_tripservice_proto_rawDescOnce sync.Once
	file_tripservice_proto_rawDescData []byte
)

func file_tripservice_proto_rawDescGZIP() []byte {
	file_tripservice_proto_rawDescOnce.Do(func() {
		file_tripservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tripservice_proto_rawDesc), len(file_tripservice_proto_rawDesc)))
	})
	return file_tripservice_proto_rawDescData
}

var file_tripservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tripservice_proto_goTypes = []any{
	(*PreviewTripRequest)(nil),  // 0: rideshare.trip.v1.PreviewTripRequest
	(*PreviewTripResponse)(nil), // 1: rideshare.trip.v1.PreviewTripResponse
	(*Coordinate)(nil),          // 2: rideshare.trip.v1.Coordinate
	(*Geometry)(nil),            // 3: rideshare.trip.v1.Geometry
	(*Route)(nil),               // 4: rideshare.trip.v1.Route
	(*RideFare)(nil),            // 5: rideshare.trip.v1.RideFare
	(*CreateTripRequest)(nil),   // 6: rideshare.trip.v1.CreateTripRequest
	(*CreateTripResponse)(nil),  // 7: rideshare.trip.v1.CreateTripResponse
}
var file_tripservice_proto_depIdxs = []int32{
	2, // 0: rideshare.trip.v1.PreviewTripRequest.pickup:type_name -> rideshare.trip.v1.Coordinate
	2, // 1: rideshare.trip.v1.PreviewTripRequest.destination:type_name -> rideshare.trip.v1.Coordinate
	4, // 2: rideshare.trip.v1.PreviewTripResponse.route:type_name -> rideshare.trip.v1.Route
	5, // 3: rideshare.trip.v1.PreviewTripResponse.ride_fares:type_name -> rideshare.trip.v1.RideFare
	2, // 4: rideshare.trip.v1.Geometry.coordinates:type_name -> rideshare.trip.v1.Coordinate
	3, // 5: rideshare.trip.v1.Route.geometry:type_name -> rideshare.trip.v1.Geometry
	0, // 6: rideshare.trip.v1.TripService.PreviewTrip:input_type -> rideshare.trip.v1.PreviewTripRequest
	1, // 7: rideshare.trip.v1.TripService.PreviewTrip:output_type -> rideshare.trip.v1.PreviewTripResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tripservice_proto_init() }
func file_tripservice_proto_init() {
	if File_tripservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tripservice_proto_rawDesc), len(file_tripservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tripservice_proto_goTypes,
		DependencyIndexes: file_tripservice_proto_depIdxs,
		MessageInfos:      file_tripservice_proto_msgTypes,
	}.Build()
	File_tripservice_proto = out.File
	file_tripservice_proto_goTypes = nil
	file_tripservice_proto_depIdxs = nil
}
